baseURL = 'https://tp.denzeliskandar.com/24T3/'
languageCode = 'en-au'
title = 'Training Program 24T3'

theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true